services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/app:/app
    ports:
      - 8000:8000
    restart: always
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    tty: true
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432

volumes:
  postgres_data:
